name: floating_text
description: A light weight flutter package that provides beautiful floating text animations.
version: 0.2.0
homepage: https://github.com/pktintali/
repository: https://github.com/pktintali/floating_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
